name: protomotions-genesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - libspatialindex=1.9.3
  - rtree=1.2.0
  - ffmpeg
  - readline
  - ncurses
  - zlib
  - tk
  - setuptools=69.5.1
  - wheel
  - pip:
      - torch==2.5.1
      - lightning>=2.5.0.post0
      - genesis-world
      - termcolor>=1.1.0
      - scikit-image
      - trimesh
      - rich
      - "smpl_sim @ git+https://github.com/ZhengyiLuo/SMPLSim.git@master"
      - typer>=0.6.1
      - transformers>=4.20.1
      - matplotlib
      - easydict
      - wandb>=0.19.8
      - tensorboardX
      - sentry-sdk==1.9.10
      - hydra-core==1.3.2
      - PyOpenGL>=3.1.4
      - moviepy
      - open3d==0.19.0 