# @package _global_

defaults:
  - smpl

robot:
  # Use the actual body names (24 bodies), not the intermediate _jointbody links
  # Genesis creates intermediate links internally, but config references actual bodies
  body_names: ['Pelvis', 'L_Hip', 'L_Knee', 'L_Ankle', 'L_Toe', 'R_Hip', 'R_Knee', 'R_Ankle', 'R_Toe', 'Torso', 'Spine', 'Chest', 'Neck', 'Head', 'L_Thorax', 'L_Shoulder', 'L_Elbow', 'L_Wrist', 'L_Hand', 'R_Thorax', 'R_Shoulder', 'R_Elbow', 'R_Wrist', 'R_Hand']
  dof_names: ['L_Hip_x', 'L_Hip_y', 'L_Hip_z', 'L_Knee_x', 'L_Knee_y', 'L_Knee_z', 'L_Ankle_x', 'L_Ankle_y', 'L_Ankle_z', 'L_Toe_x', 'L_Toe_y', 'L_Toe_z', 'R_Hip_x', 'R_Hip_y', 'R_Hip_z', 'R_Knee_x', 'R_Knee_y', 'R_Knee_z', 'R_Ankle_x', 'R_Ankle_y', 'R_Ankle_z', 'R_Toe_x', 'R_Toe_y', 'R_Toe_z', 'Torso_x', 'Torso_y', 'Torso_z', 'Spine_x', 'Spine_y', 'Spine_z', 'Chest_x', 'Chest_y', 'Chest_z', 'Neck_x', 'Neck_y', 'Neck_z', 'Head_x', 'Head_y', 'Head_z', 'L_Thorax_x', 'L_Thorax_y', 'L_Thorax_z', 'L_Shoulder_x', 'L_Shoulder_y', 'L_Shoulder_z', 'L_Elbow_x', 'L_Elbow_y', 'L_Elbow_z', 'L_Wrist_x', 'L_Wrist_y', 'L_Wrist_z', 'L_Hand_x', 'L_Hand_y', 'L_Hand_z', 'R_Thorax_x', 'R_Thorax_y', 'R_Thorax_z', 'R_Shoulder_x', 'R_Shoulder_y', 'R_Shoulder_z', 'R_Elbow_x', 'R_Elbow_y', 'R_Elbow_z', 'R_Wrist_x', 'R_Wrist_y', 'R_Wrist_z', 'R_Hand_x', 'R_Hand_y', 'R_Hand_z']
  trackable_bodies_subset: ['Pelvis', 'L_Ankle', 'R_Ankle', 'L_Hand', 'R_Hand', 'Head']

  # Observation parameters (24 bodies)
  self_obs_max_coords_size: 358  # 1 + 24 * (3 + 6 + 3 + 3) - 3

  # dof_body_ids maps each DOF to its body index in body_names
  dof_body_ids: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
  joint_axis: ['xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz']

  key_bodies: [ "R_Ankle", "L_Ankle", "L_Hand", "R_Hand" ]
  non_termination_contact_bodies: [ "R_Ankle", "L_Ankle", "R_Toe", "L_Toe" ]
  right_foot_name: "R_Ankle"
  left_foot_name: "L_Ankle"
  head_body_name: "Head"

  init_state:
    pos: [ 0.0, 0.0, 1.0 ] # x,y,z [m]
    default_joint_angles: # = target angles [rad] when action = 0.0
      L_Hip_x: 0.0
      L_Hip_y: 0.0
      L_Hip_z: 0.0
      L_Knee_x: 0.0
      L_Knee_y: 0.0
      L_Knee_z: 0.0
      L_Ankle_x: 0.0
      L_Ankle_y: 0.0
      L_Ankle_z: 0.0
      L_Toe_x: 0.0
      L_Toe_y: 0.0
      L_Toe_z: 0.0
      R_Hip_x: 0.0
      R_Hip_y: 0.0
      R_Hip_z: 0.0
      R_Knee_x: 0.0
      R_Knee_y: 0.0
      R_Knee_z: 0.0
      R_Ankle_x: 0.0
      R_Ankle_y: 0.0
      R_Ankle_z: 0.0
      R_Toe_x: 0.0
      R_Toe_y: 0.0
      R_Toe_z: 0.0
      Torso_x: 0.0
      Torso_y: 0.0
      Torso_z: 0.0
      Spine_x: 0.0
      Spine_y: 0.0
      Spine_z: 0.0
      Chest_x: 0.0
      Chest_y: 0.0
      Chest_z: 0.0
      Neck_x: 0.0
      Neck_y: 0.0
      Neck_z: 0.0
      Head_x: 0.0
      Head_y: 0.0
      Head_z: 0.0
      L_Thorax_x: 0.0
      L_Thorax_y: 0.0
      L_Thorax_z: 0.0
      L_Shoulder_x: 0.0
      L_Shoulder_y: 0.0
      L_Shoulder_z: 0.0
      L_Elbow_x: 0.0
      L_Elbow_y: 0.0
      L_Elbow_z: 0.0
      L_Wrist_x: 0.0
      L_Wrist_y: 0.0
      L_Wrist_z: 0.0
      L_Hand_x: 0.0
      L_Hand_y: 0.0
      L_Hand_z: 0.0
      R_Thorax_x: 0.0
      R_Thorax_y: 0.0
      R_Thorax_z: 0.0
      R_Shoulder_x: 0.0
      R_Shoulder_y: 0.0
      R_Shoulder_z: 0.0
      R_Elbow_x: 0.0
      R_Elbow_y: 0.0
      R_Elbow_z: 0.0
      R_Wrist_x: 0.0
      R_Wrist_y: 0.0
      R_Wrist_z: 0.0
      R_Hand_x: 0.0
      R_Hand_y: 0.0
      R_Hand_z: 0.0

  control:
    control_type: built_in_pd
    use_biased_controller: False
    map_actions_to_pd_range: True
    # PD Drive parameters (using moderate gains for SMPL humanoid)
    stiffness: # [N*m/rad]
      Hip: 150
      Knee: 200
      Ankle: 40
      Toe: 20
      Torso: 100
      Spine: 100
      Chest: 100
      Neck: 50
      Head: 50
      Thorax: 80
      Shoulder: 80
      Elbow: 60
      Wrist: 40
      Hand: 20
    damping: # [N*m*s/rad]
      Hip: 5
      Knee: 6
      Ankle: 2
      Toe: 1
      Torso: 3
      Spine: 3
      Chest: 3
      Neck: 2
      Head: 2
      Thorax: 3
      Shoulder: 3
      Elbow: 2
      Wrist: 2
      Hand: 1

  asset:
    asset_file_name: "mjcf/smpl_humanoid.xml" 