# First we define the global structures that will be used by all the configs.
defaults:
  - base/fabric
  - base/hydra
  - base/structure
  - _self_

# These are global variables that all levels of the config can access.
## Experiment setup
seed: 0
training_max_steps: 10000000000
codebase_version: 1.0  # this is recorded to enable auto-conversion of models between different versions of the codebase
headless: True
sync_motion: False

### Checkpoint logic
checkpoint: null

# Recorder behavior flags (for extras/record_rollout.py)
ignore_done: false
stop_on_done: false
auto_reset_on_done: true
deterministic: true

### Naming and dir structure
experiment_name: record_rollout
base_dir: results
save_dir: ${base_dir}/${experiment_name}

eval_overrides:
  headless: False
  num_envs: 1
